name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend (tests)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: sqlite3, pdo_sqlite, pdo_pgsql
          coverage: none
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare environment
        run: |
          cp -n .env.example .env || true
          php artisan key:generate --force
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations (SQLite)
        run: php artisan migrate --force

      - name: Upload vendor directory
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor

      - name: Upload storage logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: laravel-logs
          path: storage/logs

  frontend:
    name: Frontend (build)
    runs-on: ubuntu-22.04
    needs: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_pgsql
          coverage: none
          tools: composer:v2

      - name: Download vendor from backend
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Upload build assets
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          if-no-files-found: error
          path: public/build
